In [2]:
import numpy as np

## Array Creation

In [5]:
print(np.zeros(10))
print(np.arange(1,100))
print(np.linspace(1,100))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[   1.            3.02040816    5.04081633    7.06122449    9.08163265
   11.10204082   13.12244898   15.14285714   17.16326531   19.18367347
   21.20408163   23.2244898    25.24489796   27.26530612   29.28571429
   31.30612245   33.32653061   35.34693878   37.36734694   39.3877551
   41.40816327   43.42857143   45.44897959   47.46938776   49.48979592
   51.51020408   53.53061224   55.55102041   57.57142857   59.59183673
   61.6122449    63.63265306   65.65306122   67.67346939   69.69387755
   71.71428571   73.73469388   75.75510204   77.7755102    79.79591837
   81.81632653   83.83673469   85.85714286   87.87755102   89.89795918
   91.91836735   9

In [30]:
height_m = [1.80, 2.15, 2.10, 2.10, 1.88, 1.76, 2.09, 2.00]
weight_kg = [73, 88, 90, 65, 55, 67, 73, 91]

# Create a numpy array from baseball: np_baseball
np_height_m = np.array(height_m)
np_weight_kg = np.array(weight_kg)

print(np_height, np_weight)

[180 215 210 210 188 176 209 200] [73 88 90 65 55 67 73 91]


# NumPy array operators

You can use the usual math operators such as: `+`, `-`, `*`, `/`. Numpy will produce an new array by calculating element-wise with the given operator.

In [31]:
# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False  True  True  True  True False  True False]
[ 19.03731747  20.40816327  14.73922902  15.56133997  16.71207161]


**NOTE**: numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as *type coercion*.
Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

# Subsetting NumPy arrays

In [32]:
# Print out the weight for 5th player
print(np_weight_kg[4])

# Print out sub-array of np_height from 2nd to 5th players
print(np_height_m[1:4])

55
[ 2.15  2.1   2.1 ]


# 2D NumPy arrays

In [33]:
players = [np_height_m, np_weight_kg]

# Create a 2D numpy array
np_players = np.transpose(np.array(players))

# Print out the shape
print(np_players.shape)

(8, 2)


# Subsetting 2D NumPy arrays

In [34]:
# Print out the 5th player
print(np_players[4, :])

# Select the entire second column (weight)
print(np_players[:, 1])

# Print out height of 2th player
print(np_players[1, 0])

[  1.88  55.  ]
[ 73.  88.  90.  65.  55.  67.  73.  91.]
2.15


# Basic statistics

In [35]:
# Print out the mean of height
print(np.mean(np_players[:, 0]))

# Print out the median of height
print(np.median(np_players[:, 0]))

# Print out the stdev of height
print(np.std(np_players[:, 0]))

# Print out the correlation between height and weight
print(np.corrcoef(np_players[:, 0], np_players[:, 1]))

1.985
2.045
0.141774468788
[[ 1.          0.50089576]
 [ 0.50089576  1.        ]]
