In [29]:
import numpy as np

In [30]:
height_m = [1.80, 2.15, 2.10, 2.10, 1.88, 1.76, 2.09, 2.00]
weight_kg = [73, 88, 90, 65, 55, 67, 73, 91]

# Create a numpy array from baseball: np_baseball
np_height_m = np.array(height_m)
np_weight_kg = np.array(weight_kg)

print(np_height, np_weight)

[180 215 210 210 188 176 209 200] [73 88 90 65 55 67 73 91]


# NumPy array operators

You can use the usual math operators such as: `+`, `-`, `*`, `/`. Numpy will produce an new array by calculating element-wise with the given operator.

In [31]:
# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False  True  True  True  True False  True False]
[ 19.03731747  20.40816327  14.73922902  15.56133997  16.71207161]


**NOTE**: numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as *type coercion*.
Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

# Subsetting NumPy arrays

In [32]:
# Print out the weight for 5th player
print(np_weight_kg[4])

# Print out sub-array of np_height from 2nd to 5th players
print(np_height_m[1:4])

55
[ 2.15  2.1   2.1 ]


# 2D NumPy arrays

In [33]:
players = [np_height_m, np_weight_kg]

# Create a 2D numpy array
np_players = np.transpose(np.array(players))

# Print out the shape
print(np_players.shape)

(8, 2)


# Subsetting 2D NumPy arrays

In [34]:
# Print out the 5th player
print(np_players[4, :])

# Select the entire second column (weight)
print(np_players[:, 1])

# Print out height of 2th player
print(np_players[1, 0])

[  1.88  55.  ]
[ 73.  88.  90.  65.  55.  67.  73.  91.]
2.15


# Basic statistics

In [35]:
# Print out the mean of height
print(np.mean(np_players[:, 0]))

# Print out the median of height
print(np.median(np_players[:, 0]))

# Print out the stdev of height
print(np.std(np_players[:, 0]))

# Print out the correlation between height and weight
print(np.corrcoef(np_players[:, 0], np_players[:, 1]))

1.985
2.045
0.141774468788
[[ 1.          0.50089576]
 [ 0.50089576  1.        ]]
