In [1]:
import numpy as np
from IPython.display import display as d

## Array Creation

In [61]:
print('From a list or tuple: ')
d(np.array([1,2,3,4,5]))
print('1D array with zeros:')
d(np.zeros(10))
print('1D array with ones:')
d(np.ones(10))
print('2D array with ones on diagonal only:')
d(np.eye(2))
print('2D array with zeros integers:')
d(np.zeros((3,4), dtype=np.int))
print('1D array with a sequence:')
d(np.arange(1,10, 2))
print('1D array with evenly spaced sequence:')
d(np.linspace(1,10, 20))
print('1D array load from txt (csv format):')
d(np.genfromtxt('numpy-load-data.csv', delimiter=','))
print('1D array full of initial value:')
np.full(10, 23)
print('1D array with random values:')
np.random.random(10)


From a list or tuple: 


array([1, 2, 3, 4, 5])

1D array with zeros:


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

1D array with ones:


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

2D array with ones on diagonal only:


array([[ 1.,  0.],
       [ 0.,  1.]])

2D array with zeros integers:


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

1D array with a sequence:


array([1, 3, 5, 7, 9])

1D array with evenly spaced sequence:


array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

1D array load from txt (csv format):


array([[ 1.,  2.,  3.,  5.],
       [ 6.,  7.,  8.,  9.]])

1D array full of initial value:
1D array with random values:


array([ 0.96695877,  0.15467208,  0.95458212,  0.94260584,  0.91551467,
        0.68404743,  0.62934841,  0.35413669,  0.74316535,  0.59110848])

In [32]:
height_m = [1.80, 2.15, 2.10, 2.10, 1.88, 1.76, 2.09, 2.00]
weight_kg = [73, 88, 90, 65, 55, 67, 73, 91]

# Create a numpy array from baseball: np_baseball
np_height_m = np.array(height_m)
np_weight_kg = np.array(weight_kg)

print('Players height and weight:')
d(np_height_m, np_weight_kg)

Players height and weight:


array([ 1.8 ,  2.15,  2.1 ,  2.1 ,  1.88,  1.76,  2.09,  2.  ])

array([73, 88, 90, 65, 55, 67, 73, 91])

# NumPy array operators

You can use the usual math operators such as: `+`, `-`, `*`, `/`. Numpy will produce an new array by calculating element-wise with the given operator.

In [33]:
# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

print('Lighter players:')
d(light)

print('BMIs of all baseball players whose BMI is below 21:')
d(bmi[light])

Lighter players:


array([False,  True,  True,  True,  True, False,  True, False], dtype=bool)

BMIs of all baseball players whose BMI is below 21:


array([ 19.03731747,  20.40816327,  14.73922902,  15.56133997,  16.71207161])

**NOTE**: numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as *type coercion*.
Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

# Subsetting NumPy arrays

In [34]:
print('Weight for 5th player:')
d(np_weight_kg[4])

print('sub-array of np_height from 2nd to 5th players:')
d(np_height_m[1:4])

Weight for 5th player:


55

sub-array of np_height from 2nd to 5th players:


array([ 2.15,  2.1 ,  2.1 ])

# 2D NumPy arrays

In [28]:
players = [np_height_m, np_weight_kg]

# Create a 2D numpy array
np_players = np.transpose(np.array(players))

print('Players array shape:')
d(np_players.shape)

print('Players array:')
d(np_players)

Players array shape:


(8, 2)

Players array:


array([[  1.8 ,  73.  ],
       [  2.15,  88.  ],
       [  2.1 ,  90.  ],
       [  2.1 ,  65.  ],
       [  1.88,  55.  ],
       [  1.76,  67.  ],
       [  2.09,  73.  ],
       [  2.  ,  91.  ]])

# Subsetting 2D NumPy arrays

In [37]:
print('The 5th player:')
d(np_players[4, :])

print('Select the entire second column (weight):')
d(np_players[:, 1])

print('Height of 2th player:')
d(np_players[1, 0])

The 5th player:


array([  1.88,  55.  ])

Select the entire second column (weight):


array([ 73.,  88.,  90.,  65.,  55.,  67.,  73.,  91.])

Height of 2th player:


2.1499999999999999

# Basic statistics

In [31]:
print('Player height mean:')
d(np_height_m.mean()) # Or from the players array: np.mean(np_players[:, 0])

print('Player height median:')
d(np.median(np_height_m))

print('Player mean on both height and weight:')
d(np_players.mean(axis=0))

print('Player height std:')
d(np_height_m.std())

print('Player max, min and sum height:')
d(np_height_m.max(), np_height_m.min(), np_height_m.sum())

print('Correlation between height and weight:')
print(np.corrcoef(np_players[:, 0], np_players[:, 1]))

Player height mean:


1.9849999999999999

Player height median:


2.0449999999999999

Player mean on both height and weight:


array([  1.985,  75.25 ])

Player height std:


0.14177446878757824

Player max, min and sum height:


2.1499999999999999

1.76

15.879999999999999

Correlation between height and weight:
[[ 1.          0.50089576]
 [ 0.50089576  1.        ]]


## Reshape

In [46]:
print('Reshape the height array to a 2D array (2x4):')
d(np_height_m.reshape((2,4)))

print('Transpose the players 2D array:')
d(np_players.transpose()) # Or np_players.T


Reshape the height array to a 2D array (2x4):


array([[ 1.8 ,  2.15,  2.1 ,  2.1 ],
       [ 1.88,  1.76,  2.09,  2.  ]])

Transpose the players 2D array:


array([[  1.8 ,   2.15,   2.1 ,   2.1 ,   1.88,   1.76,   2.09,   2.  ],
       [ 73.  ,  88.  ,  90.  ,  65.  ,  55.  ,  67.  ,  73.  ,  91.  ]])

array([[  1.8 ,  73.  ],
       [  2.15,  88.  ],
       [  2.1 ,  90.  ],
       [  2.1 ,  65.  ],
       [  1.88,  55.  ],
       [  1.76,  67.  ],
       [  2.09,  73.  ],
       [  2.  ,  91.  ]])

## More operations

In [59]:
print('Cumulative sum of the Player heights:')
d(np_height_m.cumsum())

print('Array copy:')
d(np_players.copy())

print('Switch data type:')
d(np_players.astype(np.int))

Cumulative sum of the Player heights:


array([  1.8 ,   3.95,   6.05,   8.15,  10.03,  11.79,  13.88,  15.88])

Array copy:


array([[  1.8 ,  73.  ],
       [  2.15,  88.  ],
       [  2.1 ,  90.  ],
       [  2.1 ,  65.  ],
       [  1.88,  55.  ],
       [  1.76,  67.  ],
       [  2.09,  73.  ],
       [  2.  ,  91.  ]])

Switch data type:


array([[ 1, 73],
       [ 2, 88],
       [ 2, 90],
       [ 2, 65],
       [ 1, 55],
       [ 1, 67],
       [ 2, 73],
       [ 2, 91]])